name: Build and deploy Azure Function App - VideoConvertFunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  DOTNET_VERSION: '6.x'  # Specify the .NET version used by your Azure Function

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Build Azure Function
        run: dotnet build VideoUploadSite/VideoConvertFunction.csproj --configuration Release

      - name: Publish Azure Function
        run: dotnet publish VideoUploadSite/VideoConvertFunction.csproj --configuration Release --output ./publish

      - name: Upload publish folder as artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-artifact
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: functionapp-artifact
          path: ./deploy-artifact

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: 'VideoConvertFunction'  # Replace with your Azure Function App name
          package: ./deploy-artifact

      - name: List contents of the deployment package
        if: failure()
        run: ls -R ./deploy-artifact
