name: Build and deploy Azure Function App - VideoConvertFunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  DOTNET_VERSION: '6.x'  # Specify the .NET version used by your Azure Function

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Display directory structure for debugging
        run: dir

      - name: Change to the function project directory
        run: cd VideoConvertFunction

      - name: Display function project directory structure for debugging
        run: dir

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Azure Function
        run: dotnet build VideoConvertFunction.csproj --configuration Release

      - name: Publish Azure Function
        run: dotnet publish VideoConvertFunction.csproj --configuration Release --output ../publish

      - name: Upload publish folder as artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-artifact
      
