name: Build and deploy ASP.Net Core app to Azure Web App - VideoUploadSite

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  DOTNET_VERSION: '7.x'

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Build and Publish Web App
        run: dotnet publish VideoUploadSite/VideoUploadSite.csproj -c Release -o ${{github.workspace}}/publish

      - name: Upload publish folder as artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: webapp-artifact
          path: ${{github.workspace}}/publish

  deploy:
    runs-on: windows-latest
    needs: build

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webapp-artifact
          path: ${{github.workspace}}/deploy-artifact

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ExamenarbeteVideoUploadSite'
          package: ${{github.workspace}}/deploy-artifact

      - name: List contents of the deployment package
        if: failure()
        run: ls -R "${{github.workspace}}/deploy-artifact"
